/* C Source File generated by BF */

#include<stdio.h>
#include<stdlib.h>

int main(int argc,char** argv){

int* arr = (int*) malloc(3000*sizeof(int));
for(int i=0;i<3000;arr[i]=0,i++);
int i = 0;
char buffer[100];

arr[ i ] += 8;
while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 4;
while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 2;
i += 1 ;arr[ i ] += 3;
i += 1 ;arr[ i ] += 3;
i += 1 ;arr[ i ] += 1;
i += -4 ;arr[ i ] += -1;
}
i += 1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
i += 2 ;arr[ i ] += 1;
while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;arr[ i ] += -1;
}
i += 2 ;printf("%c", arr[ i ] );
i += 1 ;arr[ i ] += -3;
printf("%c", arr[ i ] );
arr[ i ] += 7;
printf("%c", arr[ i ] );
printf("%c", arr[ i ] );
arr[ i ] += 3;
printf("%c", arr[ i ] );
i += 2 ;printf("%c", arr[ i ] );
i += -1 ;arr[ i ] += -1;
printf("%c", arr[ i ] );
i += -1 ;printf("%c", arr[ i ] );
arr[ i ] += 3;
printf("%c", arr[ i ] );
arr[ i ] += -6;
printf("%c", arr[ i ] );
arr[ i ] += -8;
printf("%c", arr[ i ] );
i += 2 ;arr[ i ] += 1;
printf("%c", arr[ i ] );
i += 1 ;arr[ i ] += 2;
printf("%c", arr[ i ] );
printf("\n");

free(arr);

}
