/* C Source File generated by BF */

#include<stdio.h>
#include<stdlib.h>

int main(int argc,char** argv){

int* arr = (int*) malloc(3000*sizeof(int));
for(int i=0;i<3000;arr[i]=0,i++);
int i = 0;
char buffer[100];

i += 20 ;fgets(buffer,100,stdin);
arr[ i ] = buffer[0];
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -32;
while ( arr[ i ] ) {
arr[ i ] += -10;
while ( arr[ i ] ) {
arr[ i ] += -1;
while ( arr[ i ] ) {
arr[ i ] += -2;
while ( arr[ i ] ) {
arr[ i ] += -2;
while ( arr[ i ] ) {
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
}
i += 1 ;while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += -1 ;arr[ i ] += 47;
i += 2 ;}
i += -1 ;while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += 1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
arr[ i ] += -1;
}
i += -1 ;fgets(buffer,100,stdin);
arr[ i ] = buffer[0];
while ( arr[ i ] ) {
arr[ i ] += -1;
}
i += -2 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += 4 ;arr[ i ] += 1;
i += -4 ;arr[ i ] += -1;
}
i += -1 ;}
i += 5 ;while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;fgets(buffer,100,stdin);
arr[ i ] = buffer[0];
while ( arr[ i ] ) {
arr[ i ] += -32;
while ( arr[ i ] ) {
arr[ i ] += 32;
i += 2 ;fgets(buffer,100,stdin);
arr[ i ] = buffer[0];
i += -1 ;}
i += 1 ;}
i += -1 ;while ( arr[ i ] ) {
i += 1 ;}
i += -1 ;while ( arr[ i ] ) {
i += 1 ;}
i += -1 ;while ( arr[ i ] ) {
i += -2 ;}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
arr[ i ] += 1;
i += 1 ;while ( arr[ i ] ) {
arr[ i ] += -45;
while ( arr[ i ] ) {
arr[ i ] += 45;
i += -1 ;arr[ i ] += -1;
i += 1 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;}
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += -3 ;arr[ i ] += 1;
i += 5 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += 2 ;}
i += -3 ;while ( arr[ i ] ) {
i += -2 ;}
i += -1 ;}
}
i += 2 ;arr[ i ] += 1;
i += 1 ;while ( arr[ i ] ) {
arr[ i ] += -45;
while ( arr[ i ] ) {
arr[ i ] += 45;
i += -1 ;arr[ i ] += -1;
i += 1 ;while ( arr[ i ] ) {
i += 2 ;}
}
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += 3 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -2 ;arr[ i ] += 1;
i += 2 ;arr[ i ] += -1;
}
i += 2 ;}
i += -4 ;while ( arr[ i ] ) {
i += -2 ;}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += -2 ;arr[ i ] += 1;
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += 1 ;arr[ i ] += -1;
i += -1 ;}
i += 1 ;while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
i += 2 ;}
i += -1 ;}
}
i += -1 ;while ( arr[ i ] ) {
i += -2 ;}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += 1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -2 ;arr[ i ] += 1;
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
i += 2 ;}
i += 6 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;arr[ i ] += 1;
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -7 ;while ( arr[ i ] ) {
i += -2 ;}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += 1 ;arr[ i ] += -1;
}
i += 1 ;while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
i += 2 ;}
i += 6 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += -1 ;while ( arr[ i ] ) {
i += -1 ;}
i += -7 ;while ( arr[ i ] ) {
i += -2 ;}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += 1 ;}
i += -3 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += 2 ;arr[ i ] += 1;
i += -2 ;arr[ i ] += -1;
}
i += -1 ;}
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
i += 2 ;}
i += 2 ;arr[ i ] += 48;
i += 4 ;while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -45;
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += -1;
i += 1 ;arr[ i ] += 45;
i += -4 ;arr[ i ] += 1;
while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -58;
while ( arr[ i ] ) {
arr[ i ] += 58;
i += 1 ;arr[ i ] += -1;
}
i += 1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += 1 ;arr[ i ] += 48;
i += -3 ;arr[ i ] += 1;
i += 1 ;}
i += -1 ;}
arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
while ( arr[ i ] ) {
arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
i += 2 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -2 ;arr[ i ] += 1;
i += 2 ;arr[ i ] += -1;
}
i += 1 ;}
i += -1 ;}
i += 1 ;while ( arr[ i ] ) {
arr[ i ] += 48;
i += 2 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
i += 1 ;}
i += -1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += -1 ;}
i += 1 ;}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += -3 ;while ( arr[ i ] ) {
i += -2 ;}
i += 2 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;while ( arr[ i ] ) {
i += 2 ;}
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;arr[ i ] += 1;
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += -3 ;while ( arr[ i ] ) {
i += -2 ;}
i += 2 ;arr[ i ] += -1;
}
i += 2 ;while ( arr[ i ] ) {
i += 2 ;}
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += -1 ;while ( arr[ i ] ) {
i += -1 ;}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += -3 ;while ( arr[ i ] ) {
i += -2 ;}
i += 2 ;}
i += -3 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += -2 ;}
i += 3 ;while ( arr[ i ] ) {
i += 2 ;}
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += -1 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;arr[ i ] += 1;
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;}
i += -2 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += -1 ;}
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += -1 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;arr[ i ] += 1;
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;}
i += -2 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += -1 ;}
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += -1 ;while ( arr[ i ] ) {
i += -1 ;}
i += -2 ;while ( arr[ i ] ) {
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += 4 ;arr[ i ] += 1;
i += -5 ;while ( arr[ i ] ) {
i += -1 ;}
i += -2 ;arr[ i ] += -1;
}
i += -1 ;while ( arr[ i ] ) {
i += -1 ;}
i += -2 ;while ( arr[ i ] ) {
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += 2 ;arr[ i ] += 1;
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += -2 ;arr[ i ] += -1;
}
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += 2 ;while ( arr[ i ] ) {
i += 2 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += -2 ;arr[ i ] += -1;
i += 1 ;}
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
i += -1 ;}
i += 1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;arr[ i ] += 1;
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 2 ;arr[ i ] += -1;
}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += -1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += -1 ;}
i += 1 ;arr[ i ] += 48;
i += -2 ;arr[ i ] += -1;
}
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 2 ;}
i += 2 ;while ( arr[ i ] ) {
i += -5 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += -1 ;}
i += -3 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += -1 ;}
i += 1 ;arr[ i ] += 48;
while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;arr[ i ] += -1;
while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += 1 ;}
i += -5 ;while ( arr[ i ] ) {
i += -1 ;}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += 1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -2 ;arr[ i ] += 1;
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
i += 1 ;}
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 2 ;arr[ i ] += 1;
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
i += -1 ;}
i += 1 ;arr[ i ] += -1;
}
i += 1 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
i += 1 ;}
i += 2 ;while ( arr[ i ] ) {
i += -2 ;arr[ i ] += 1;
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 4 ;arr[ i ] += 1;
i += -5 ;while ( arr[ i ] ) {
i += -1 ;}
i += 1 ;arr[ i ] += -1;
}
i += 1 ;while ( arr[ i ] ) {
i += 1 ;}
i += 2 ;while ( arr[ i ] ) {
i += 2 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += -2 ;arr[ i ] += -1;
i += 1 ;}
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
i += -1 ;}
i += 1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
arr[ i ] += -1;
}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += 1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -2 ;arr[ i ] += 1;
i += 2 ;arr[ i ] += -1;
}
i += 1 ;}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
i += -1 ;}
i += 1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -2 ;arr[ i ] += 1;
i += 2 ;arr[ i ] += -1;
}
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
i += 1 ;}
i += 4 ;}
i += 2 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
arr[ i ] += -1;
}
i += -5 ;while ( arr[ i ] ) {
i += -1 ;}
i += 1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -2 ;arr[ i ] += 1;
i += 2 ;arr[ i ] += -1;
}
i += 1 ;}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
i += -1 ;}
i += 1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -2 ;arr[ i ] += 1;
i += 2 ;arr[ i ] += -1;
}
i += 1 ;}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;arr[ i ] += 1;
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += 6 ;}
i += -5 ;while ( arr[ i ] ) {
i += -1 ;}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
i += -1 ;}
i += 1 ;}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
i += -1 ;}
i += -2 ;arr[ i ] += 1;
i += 1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += -1 ;while ( arr[ i ] ) {
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;arr[ i ] += 1;
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
i += -1 ;}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;arr[ i ] += -1;
}
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += -1 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
i += -1 ;}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;arr[ i ] += 1;
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += 1 ;}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += 2 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += 1 ;}
i += 2 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += 1 ;}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;}
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += -1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += -1 ;}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
}
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += -1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += 2 ;arr[ i ] += 1;
i += -2 ;arr[ i ] += -1;
}
i += -1 ;}
i += -3 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += 2 ;arr[ i ] += 1;
i += -2 ;arr[ i ] += -1;
}
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += -1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += 1 ;while ( arr[ i ] ) {
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;arr[ i ] += 1;
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += 1 ;arr[ i ] += -1;
}
i += 1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += -1 ;arr[ i ] += 9;
i += -1 ;arr[ i ] += -1;
i += 3 ;}
i += 1 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;arr[ i ] += -1;
}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
i += -1 ;}
i += -2 ;while ( arr[ i ] ) {
i += 2 ;arr[ i ] += 1;
i += -2 ;arr[ i ] += -1;
}
i += 2 ;arr[ i ] += 48;
while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
i += 1 ;}
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
i += -1 ;}
i += 1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += 1 ;}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -4 ;while ( arr[ i ] ) {
i += -1 ;}
arr[ i ] += 1;
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += 1 ;arr[ i ] += -1;
i += 1 ;while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;arr[ i ] += 45;
i += -4 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;}
i += 1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += 1 ;while ( arr[ i ] ) {
i += 1 ;}
i += 4 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += 1 ;}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
}
i += 1 ;while ( arr[ i ] ) {
i += 1 ;}
i += 2 ;}
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += -1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
arr[ i ] += -1;
}
i += -1 ;}
i += -2 ;}
i += 2 ;}
i += -4 ;arr[ i ] += -1;
while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -47;
while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += 1 ;arr[ i ] += 46;
while ( arr[ i ] ) {
i += 1 ;}
}
i += 1 ;while ( arr[ i ] ) {
arr[ i ] += 56;
i += -2 ;arr[ i ] += -1;
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;}
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += -1 ;arr[ i ] += 1;
while ( arr[ i ] ) {
i += -1 ;}
i += 1 ;while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -48;
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += -1;
i += 1 ;arr[ i ] += 48;
while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -3 ;arr[ i ] += 1;
i += 3 ;arr[ i ] += -1;
}
i += 1 ;}
i += -2 ;}
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += 2 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += 1 ;}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
}
i += 1 ;}
i += -2 ;arr[ i ] += -1;
while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
arr[ i ] += -1;
}
i += 2 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -2 ;arr[ i ] += 1;
i += 2 ;arr[ i ] += -1;
}
i += 1 ;}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;}
i += 2 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -2 ;arr[ i ] += 1;
i += 2 ;arr[ i ] += -1;
}
i += 1 ;}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
arr[ i ] += -1;
}
i += 2 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += 1 ;}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;}
i += 2 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -3 ;arr[ i ] += 1;
i += 3 ;arr[ i ] += -1;
}
i += 1 ;}
i += -4 ;while ( arr[ i ] ) {
i += -1 ;}
i += -2 ;arr[ i ] += 1;
i += 1 ;while ( arr[ i ] ) {
i += -1 ;arr[ i ] += -1;
i += 1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
}
i += 1 ;arr[ i ] += 45;
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += 3 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += 1 ;}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;}
i += 2 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += 1 ;}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
arr[ i ] += 1;
i += 1 ;arr[ i ] += -45;
while ( arr[ i ] ) {
arr[ i ] += 45;
i += -1 ;arr[ i ] += -1;
i += 1 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;}
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += 1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -48;
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 44;
i += 1 ;arr[ i ] += 48;
while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;}
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += 47;
i += 1 ;}
}
i += 2 ;}
}
i += -1 ;while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += 1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
arr[ i ] += -1;
}
i += -1 ;arr[ i ] += 1;
i += 1 ;fgets(buffer,100,stdin);
arr[ i ] = buffer[0];
arr[ i ] += -32;
while ( arr[ i ] ) {
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
}
i += 1 ;arr[ i ] += 32;
i += -1 ;arr[ i ] += 45;
i += 3 ;}
i += -1 ;while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += 1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
arr[ i ] += -1;
}
i += -1 ;arr[ i ] += 43;
i += 1 ;arr[ i ] += 1;
i += 1 ;fgets(buffer,100,stdin);
arr[ i ] = buffer[0];
arr[ i ] += -45;
while ( arr[ i ] ) {
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
}
i += 1 ;while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
arr[ i ] += 45;
i += 1 ;arr[ i ] += 45;
i += 2 ;}
i += -1 ;while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += 1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
arr[ i ] += -1;
}
}
}
}
}
i += -1 ;while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += 1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
arr[ i ] += -1;
}
i += -1 ;arr[ i ] += 43;
i += 2 ;}
}
i += -1 ;while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += 1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
arr[ i ] += -1;
}
i += -1 ;fgets(buffer,100,stdin);
arr[ i ] = buffer[0];
while ( arr[ i ] ) {
arr[ i ] += -1;
}
i += -2 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += 4 ;arr[ i ] += 1;
i += -4 ;arr[ i ] += -1;
}
i += -1 ;}
i += 5 ;while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;fgets(buffer,100,stdin);
arr[ i ] = buffer[0];
while ( arr[ i ] ) {
arr[ i ] += -32;
while ( arr[ i ] ) {
arr[ i ] += 32;
i += 2 ;fgets(buffer,100,stdin);
arr[ i ] = buffer[0];
i += -1 ;}
i += 1 ;}
i += -1 ;while ( arr[ i ] ) {
i += 1 ;}
i += -1 ;while ( arr[ i ] ) {
i += 1 ;}
i += -1 ;while ( arr[ i ] ) {
i += -2 ;}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
arr[ i ] += 1;
i += 1 ;while ( arr[ i ] ) {
arr[ i ] += -45;
while ( arr[ i ] ) {
arr[ i ] += 45;
i += -1 ;arr[ i ] += -1;
i += 1 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;}
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += -3 ;arr[ i ] += 1;
i += 5 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += 2 ;}
i += -3 ;while ( arr[ i ] ) {
i += -2 ;}
i += -1 ;}
}
i += 2 ;arr[ i ] += 1;
i += 1 ;while ( arr[ i ] ) {
arr[ i ] += -45;
while ( arr[ i ] ) {
arr[ i ] += 45;
i += -1 ;arr[ i ] += -1;
i += 1 ;while ( arr[ i ] ) {
i += 2 ;}
}
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += 3 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -2 ;arr[ i ] += 1;
i += 2 ;arr[ i ] += -1;
}
i += 2 ;}
i += -4 ;while ( arr[ i ] ) {
i += -2 ;}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += -2 ;arr[ i ] += 1;
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += 1 ;arr[ i ] += -1;
i += -1 ;}
i += 1 ;while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
i += 2 ;}
i += -1 ;}
}
i += 9 ;arr[ i ] += 48;
i += -10 ;while ( arr[ i ] ) {
i += -2 ;}
i += -2 ;while ( arr[ i ] ) {
arr[ i ] += -48;
while ( arr[ i ] ) {
i += 4 ;while ( arr[ i ] ) {
i += 2 ;}
i += 8 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;}
arr[ i ] += 43;
while ( arr[ i ] ) {
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;}
i += -8 ;while ( arr[ i ] ) {
i += -2 ;}
i += 2 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;while ( arr[ i ] ) {
i += 2 ;}
i += 8 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;}
i += 1 ;arr[ i ] += 1;
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;}
i += -8 ;while ( arr[ i ] ) {
i += -2 ;}
i += 2 ;arr[ i ] += -1;
}
i += 2 ;while ( arr[ i ] ) {
i += 2 ;}
i += 8 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
i += -2 ;arr[ i ] += 1;
i += 2 ;arr[ i ] += -1;
}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;}
i += -8 ;while ( arr[ i ] ) {
i += -2 ;}
i += 2 ;}
i += -3 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += -2 ;}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -2 ;while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
i += 2 ;}
i += 8 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;}
i += -1 ;arr[ i ] += 48;
while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;}
i += -8 ;while ( arr[ i ] ) {
i += -2 ;}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += -2 ;arr[ i ] += -1;
}
i += 1 ;while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
i += 2 ;}
i += 8 ;while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
}
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += -1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;}
i += -2 ;arr[ i ] += 1;
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += -48;
while ( arr[ i ] ) {
i += 4 ;while ( arr[ i ] ) {
i += 1 ;}
i += -1 ;arr[ i ] += 1;
while ( arr[ i ] ) {
i += -1 ;}
i += -3 ;arr[ i ] += -1;
}
i += 1 ;arr[ i ] += -1;
i += 3 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += 1 ;}
i += 1 ;}
i += -3 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;}
i += -1 ;}
i += 1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += 1 ;}
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += -1 ;while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += -1 ;}
i += -3 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += 3 ;arr[ i ] += 1;
i += -3 ;arr[ i ] += -1;
}
i += -1 ;}
i += 4 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += 1 ;}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
arr[ i ] += 48;
while ( arr[ i ] ) {
i += 1 ;}
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += -48;
while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += 1 ;while ( arr[ i ] ) {
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;arr[ i ] += 1;
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;arr[ i ] += -1;
}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -2 ;arr[ i ] += 10;
i += 1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += -1 ;arr[ i ] += -1;
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += -2 ;}
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += 1;
while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += -1 ;arr[ i ] += 1;
i += -2 ;}
i += 5 ;}
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
}
i += -1 ;while ( arr[ i ] ) {
i += 4 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;arr[ i ] += 1;
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -3 ;arr[ i ] += -1;
}
i += 4 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;arr[ i ] += 48;
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -4 ;while ( arr[ i ] ) {
i += 5 ;while ( arr[ i ] ) {
i += 1 ;}
i += -1 ;arr[ i ] += 1;
while ( arr[ i ] ) {
i += -1 ;}
i += -4 ;arr[ i ] += -1;
}
i += 5 ;while ( arr[ i ] ) {
i += 1 ;}
i += -1 ;}
i += 2 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -3 ;arr[ i ] += 1;
i += 3 ;arr[ i ] += -1;
}
i += 1 ;}
i += -4 ;while ( arr[ i ] ) {
i += -1 ;}
i += 0 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -48;
while ( arr[ i ] ) {
arr[ i ] += 48;
i += -1 ;arr[ i ] += -1;
}
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += 2 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += 1 ;}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;}
i += -8 ;while ( arr[ i ] ) {
i += -2 ;}
i += -2 ;arr[ i ] += -1;
}
i += 4 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += 2 ;}
i += 8 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += 1 ;}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -9 ;while ( arr[ i ] ) {
i += -2 ;}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -2 ;arr[ i ] += 1;
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += -1 ;}
i += -2 ;while ( arr[ i ] ) {
arr[ i ] += -1;
}
i += 6 ;while ( arr[ i ] ) {
i += 2 ;}
i += -2 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
arr[ i ] += -1;
}
i += 10 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -2 ;arr[ i ] += 1;
i += 2 ;arr[ i ] += -1;
}
i += 1 ;}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += -9 ;}
i += 10 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -13 ;arr[ i ] += 1;
i += 13 ;arr[ i ] += -1;
}
i += 1 ;}
i += -14 ;while ( arr[ i ] ) {
i += -1 ;}
i += -2 ;arr[ i ] += 1;
i += 1 ;while ( arr[ i ] ) {
i += -1 ;arr[ i ] += -1;
i += 1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
}
i += 1 ;arr[ i ] += 45;
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += 3 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += 1 ;}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;}
i += 2 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += 1 ;}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
arr[ i ] += 1;
i += 1 ;arr[ i ] += -45;
while ( arr[ i ] ) {
arr[ i ] += 45;
i += -1 ;arr[ i ] += -1;
i += 1 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;}
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += 1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -48;
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 44;
i += 1 ;arr[ i ] += 48;
while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;}
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += 47;
i += 1 ;}
}
i += 2 ;}
}
i += -1 ;while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += 1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
arr[ i ] += -1;
}
i += 1 ;}
fgets(buffer,100,stdin);
arr[ i ] = buffer[0];
i += 1 ;arr[ i ] += 1;
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += 1;
while ( arr[ i ] ) {
arr[ i ] += -1;
i += 1 ;arr[ i ] += -1;
}
i += 1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += 1 ;}
i += -1 ;}
i += 1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += 1 ;}
i += -2 ;}
i += -2 ;while ( arr[ i ] ) {
i += 1 ;}
i += -1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;}
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
arr[ i ] += -1;
}
i += 1 ;arr[ i ] += 1;
i += 1 ;while ( arr[ i ] ) {
arr[ i ] += -45;
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += -1;
i += 1 ;arr[ i ] += 45;
i += -4 ;while ( arr[ i ] ) {
i += -1 ;}
arr[ i ] += 1;
i += 1 ;arr[ i ] += -45;
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += -1;
i += 1 ;arr[ i ] += 45;
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += -2 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += 1;
i += 3 ;}
}
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += -3 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += -1 ;}
i += 1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -45;
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += -1;
i += 1 ;arr[ i ] += 45;
i += -5 ;arr[ i ] += 1;
i += 4 ;}
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += -2 ;arr[ i ] += 1;
i += 2 ;}
i += -1 ;}
}
i += -3 ;arr[ i ] += 1;
i += 1 ;while ( arr[ i ] ) {
i += -1 ;arr[ i ] += -1;
i += 1 ;arr[ i ] += -1;
i += 5 ;while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += -3 ;while ( arr[ i ] ) {
i += 4 ;while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;arr[ i ] += 1;
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += -3 ;arr[ i ] += -1;
}
i += 4 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -5 ;arr[ i ] += 1;
i += 5 ;arr[ i ] += -1;
}
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -5 ;arr[ i ] += 1;
i += 5 ;arr[ i ] += -1;
}
i += 1 ;}
i += -6 ;while ( arr[ i ] ) {
i += -1 ;}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += 1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += -1 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;arr[ i ] += 1;
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;}
i += -2 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += -1 ;}
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += -1 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;arr[ i ] += 1;
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;}
i += -2 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += -1 ;}
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += -1 ;while ( arr[ i ] ) {
i += -1 ;}
i += -2 ;while ( arr[ i ] ) {
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += 4 ;arr[ i ] += 1;
i += -5 ;while ( arr[ i ] ) {
i += -1 ;}
i += -2 ;arr[ i ] += -1;
}
i += -1 ;while ( arr[ i ] ) {
i += -1 ;}
i += -2 ;while ( arr[ i ] ) {
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += 2 ;arr[ i ] += 1;
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += -2 ;arr[ i ] += -1;
}
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += 2 ;while ( arr[ i ] ) {
i += 2 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += -2 ;arr[ i ] += -1;
i += 1 ;}
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
i += -1 ;}
i += 1 ;while ( arr[ i ] ) {
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
arr[ i ] += 48;
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += 1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += 1 ;}
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 2 ;arr[ i ] += -1;
}
i += 2 ;while ( arr[ i ] ) {
i += -5 ;while ( arr[ i ] ) {
i += -1 ;}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
arr[ i ] += 48;
while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += 4 ;arr[ i ] += -1;
}
i += -5 ;while ( arr[ i ] ) {
i += -1 ;}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += 1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -2 ;arr[ i ] += 1;
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
i += 1 ;}
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 2 ;arr[ i ] += 1;
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
i += -1 ;}
i += 1 ;arr[ i ] += -1;
}
i += 1 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
i += 1 ;}
i += 2 ;while ( arr[ i ] ) {
i += -2 ;arr[ i ] += 1;
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 4 ;arr[ i ] += 1;
i += -5 ;while ( arr[ i ] ) {
i += -1 ;}
i += 1 ;arr[ i ] += -1;
}
i += 1 ;while ( arr[ i ] ) {
i += 1 ;}
i += 2 ;while ( arr[ i ] ) {
i += 2 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += -2 ;arr[ i ] += -1;
i += 1 ;}
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
i += -1 ;}
i += 1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
arr[ i ] += -1;
}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += 1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -2 ;arr[ i ] += 1;
i += 2 ;arr[ i ] += -1;
}
i += 1 ;}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
i += -1 ;}
i += 1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -2 ;arr[ i ] += 1;
i += 2 ;arr[ i ] += -1;
}
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
i += 1 ;}
i += 4 ;}
i += 2 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
arr[ i ] += -1;
}
i += -5 ;while ( arr[ i ] ) {
i += -1 ;}
i += 1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -2 ;arr[ i ] += 1;
i += 2 ;arr[ i ] += -1;
}
i += 1 ;}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
i += -1 ;}
i += 1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -2 ;arr[ i ] += 1;
i += 2 ;arr[ i ] += -1;
}
i += 1 ;}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;arr[ i ] += 1;
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += 6 ;}
i += -5 ;while ( arr[ i ] ) {
i += -1 ;}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
i += -1 ;}
i += 1 ;}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
arr[ i ] += 1;
i += -1 ;while ( arr[ i ] ) {
i += 1 ;arr[ i ] += -1;
i += -1 ;while ( arr[ i ] ) {
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += 8 ;arr[ i ] += -1;
i += -9 ;while ( arr[ i ] ) {
i += -1 ;}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;arr[ i ] += -1;
}
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += -1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += 2 ;arr[ i ] += 1;
i += -2 ;arr[ i ] += -1;
}
i += -1 ;}
i += -3 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += 2 ;arr[ i ] += 1;
i += -2 ;arr[ i ] += -1;
}
i += -1 ;}
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += 1 ;while ( arr[ i ] ) {
i += 1 ;}
i += -1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;arr[ i ] += 1;
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
i += -1 ;}
i += -2 ;arr[ i ] += -1;
}
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
i += 1 ;}
i += -1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += 1 ;while ( arr[ i ] ) {
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;arr[ i ] += 1;
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;arr[ i ] += -1;
}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
}
i += -2 ;}
i += 1 ;}
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += -1 ;while ( arr[ i ] ) {
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += -1 ;while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += -1 ;while ( arr[ i ] ) {
i += -1 ;}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
arr[ i ] += 1;
i += 1 ;while ( arr[ i ] ) {
i += -1 ;arr[ i ] += -1;
i += 1 ;arr[ i ] += -1;
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
}
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += -1 ;arr[ i ] += -1;
i += 2 ;arr[ i ] += 9;
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;arr[ i ] += -1;
}
i += 1 ;arr[ i ] += 1;
while ( arr[ i ] ) {
i += 1 ;}
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;arr[ i ] += 48;
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;}
i += 2 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
arr[ i ] += -1;
}
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += -1 ;arr[ i ] += 1;
while ( arr[ i ] ) {
i += -1 ;}
i += 1 ;while ( arr[ i ] ) {
arr[ i ] += -48;
while ( arr[ i ] ) {
arr[ i ] += 48;
while ( arr[ i ] ) {
i += 1 ;}
}
i += 1 ;}
i += -1 ;while ( arr[ i ] ) {
i += 1 ;}
i += -1 ;arr[ i ] += -1;
while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += 4 ;arr[ i ] += 1;
i += -4 ;arr[ i ] += -1;
}
i += -1 ;}
i += 5 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
arr[ i ] += -1;
}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
arr[ i ] += 45;
while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
}
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += 6 ;while ( arr[ i ] ) {
i += 1 ;}
i += 3 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += -2 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;}
i += -3 ;while ( arr[ i ] ) {
arr[ i ] += -48;
while ( arr[ i ] ) {
i += 4 ;while ( arr[ i ] ) {
i += 1 ;}
i += -1 ;arr[ i ] += 1;
while ( arr[ i ] ) {
i += -1 ;}
i += -3 ;arr[ i ] += -1;
}
}
arr[ i ] += 1;
i += -1 ;while ( arr[ i ] ) {
i += 1 ;arr[ i ] += -1;
i += -1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += -1 ;}
i += -3 ;while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += 5 ;while ( arr[ i ] ) {
i += 1 ;}
}
i += 1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += 2 ;}
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += -1 ;while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += -1 ;}
i += -3 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += 3 ;arr[ i ] += 1;
i += -3 ;arr[ i ] += -1;
}
i += -1 ;}
i += 1 ;}
i += -4 ;while ( arr[ i ] ) {
i += 3 ;arr[ i ] += 1;
i += -3 ;arr[ i ] += -1;
}
i += 3 ;while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += 4 ;while ( arr[ i ] ) {
i += -3 ;while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += 2 ;}
i += 1 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += 1 ;}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -3 ;while ( arr[ i ] ) {
i += 4 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;arr[ i ] += 1;
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -3 ;arr[ i ] += -1;
}
i += 4 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -2 ;arr[ i ] += 1;
i += 2 ;arr[ i ] += -1;
}
i += 1 ;}
i += -4 ;while ( arr[ i ] ) {
i += -1 ;}
arr[ i ] += 48;
while ( arr[ i ] ) {
i += 1 ;}
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += -48;
while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += 1 ;while ( arr[ i ] ) {
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;arr[ i ] += 1;
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;arr[ i ] += -1;
}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -2 ;arr[ i ] += 10;
i += 1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += -1 ;arr[ i ] += -1;
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += -2 ;}
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += 1;
while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += -1 ;arr[ i ] += 1;
i += -2 ;}
i += 5 ;}
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
}
i += -1 ;while ( arr[ i ] ) {
i += 4 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;arr[ i ] += 1;
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -3 ;arr[ i ] += -1;
}
i += 4 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;arr[ i ] += 48;
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += -4 ;while ( arr[ i ] ) {
i += 5 ;while ( arr[ i ] ) {
i += 1 ;}
i += -1 ;arr[ i ] += 1;
while ( arr[ i ] ) {
i += -1 ;}
i += -4 ;arr[ i ] += -1;
}
i += 5 ;while ( arr[ i ] ) {
i += 1 ;}
i += -1 ;}
i += 2 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += 1 ;}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += 1 ;while ( arr[ i ] ) {
arr[ i ] += -48;
while ( arr[ i ] ) {
arr[ i ] += 48;
while ( arr[ i ] ) {
i += 1 ;}
}
i += 1 ;}
i += -1 ;arr[ i ] += 1;
i += -1 ;while ( arr[ i ] ) {
i += 1 ;arr[ i ] += -1;
i += -1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += -1 ;}
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
}
i += 1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += 1 ;arr[ i ] += 48;
i += 2 ;}
arr[ i ] += 1;
i += 1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += -1 ;arr[ i ] += -1;
i += -2 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += -1 ;}
i += 1 ;arr[ i ] += 45;
while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;}
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += -2 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += -1 ;}
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
}
i += 2 ;while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += -3 ;while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;}
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;}
i += -2 ;while ( arr[ i ] ) {
i += -1 ;}
i += 1 ;while ( arr[ i ] ) {
i += 1 ;}
printf("\n");

free(arr);

}
