/* C Source File generated by BF */

#include<stdio.h>
#include<stdlib.h>

int main(int argc,char** argv){

int* arr = (int*) malloc(3000*sizeof(int));
for(int i=0;i<3000;arr[i]=0,i++);
int i = 0;
char buffer[100];

arr[ i ] += -3;
i += 1 ;arr[ i ] += -3;
i += 4 ;arr[ i ] += -1;
i += 1 ;arr[ i ] += -1;
i += 1 ;arr[ i ] += -1;
i += 5 ;arr[ i ] += -2;
i += 18 ;arr[ i ] += 1;
i += 2 ;arr[ i ] += 10;
while ( arr[ i ] ) {
i += -2 ;arr[ i ] += 2;
while ( arr[ i ] ) {
arr[ i ] += -2;
i += -1 ;arr[ i ] += 1;
i += -2 ;arr[ i ] += 1;
i += -2 ;arr[ i ] += 1;
i += 4 ;while ( arr[ i ] ) {
i += 1 ;while ( arr[ i ] ) {
i += -1 ;arr[ i ] += -1;
i += 2 ;arr[ i ] += 3;
i += 2 ;while ( arr[ i ] ) {
arr[ i ] += -1;
}
arr[ i ] += 3;
i += -3 ;arr[ i ] += 1;
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 2;
i += 2 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -2;
}
}
arr[ i ] += 1;
i += 1 ;arr[ i ] += 5;
while ( arr[ i ] ) {
i += 2 ;arr[ i ] += 9;
i += -2 ;arr[ i ] += -1;
}
i += 2 ;arr[ i ] += 4;
printf("%c", arr[ i ] );
while ( arr[ i ] ) {
arr[ i ] += -1;
}
i += 2 ;arr[ i ] += 1;
while ( arr[ i ] ) {
i += -4 ;arr[ i ] += 1;
i += 2 ;arr[ i ] += 1;
i += 2 ;arr[ i ] += -1;
}
i += -6 ;while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += -2 ;}
arr[ i ] += 10;
printf("%c", arr[ i ] );
while ( arr[ i ] ) {
arr[ i ] += -1;
}
i += 1 ;arr[ i ] += 2;
}
arr[ i ] += -2;
i += 2 ;while ( arr[ i ] ) {
arr[ i ] += -2;
i += 1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
}
i += 1 ;}
i += -2 ;while ( arr[ i ] ) {
i += 2 ;arr[ i ] += -2;
while ( arr[ i ] ) {
arr[ i ] += -1;
while ( arr[ i ] ) {
arr[ i ] += -1;
while ( arr[ i ] ) {
arr[ i ] += -5;
while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += 7;
i += -2 ;arr[ i ] += 1;
}
arr[ i ] += -2;
i += 2 ;arr[ i ] += -1;
printf("%c", arr[ i ] );
arr[ i ] += -5;
i += 1 ;fgets(buffer,100,stdin);
arr[ i ] = buffer[0];
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += -1;
i += 1 ;arr[ i ] += -1;
}
i += -1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;}
arr[ i ] += 1;
while ( arr[ i ] ) {
arr[ i ] += -1;
i += 2 ;}
i += -1 ;arr[ i ] += -1;
}
i += -1 ;while ( arr[ i ] ) {
i += -2 ;fgets(buffer,100,stdin);
arr[ i ] = buffer[0];
while ( arr[ i ] ) {
arr[ i ] += -1;
}
}
i += 4 ;}
i += 1 ;}
i += -1 ;while ( arr[ i ] ) {
i += 1 ;arr[ i ] += -1;
while ( arr[ i ] ) {
arr[ i ] += 1;
i += -1 ;arr[ i ] += 3;
}
arr[ i ] += 1;
i += -1 ;arr[ i ] += 3;
while ( arr[ i ] ) {
arr[ i ] += 1;
while ( arr[ i ] ) {
arr[ i ] += -4;
i += 1 ;}
arr[ i ] += 1;
i += -6 ;while ( arr[ i ] ) {
i += 2 ;}
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
}
}
i += 1 ;while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
while ( arr[ i ] ) {
arr[ i ] += -4;
i += 1 ;}
arr[ i ] += 2;
while ( arr[ i ] ) {
i += -1 ;}
i += -1 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += 1 ;}
arr[ i ] += 1;
i += 1 ;arr[ i ] += 9;
i += -2 ;arr[ i ] += -1;
while ( arr[ i ] ) {
i += -1 ;}
}
}
i += 1 ;while ( arr[ i ] ) {
i += 4 ;}
}
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += 1;
i += -2 ;arr[ i ] += -1;
}
i += 1 ;while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
arr[ i ] += 2;
i += 1 ;arr[ i ] += 1;
i += 2 ;}
i += -1 ;while ( arr[ i ] ) {
i += -2 ;arr[ i ] += 2;
while ( arr[ i ] ) {
arr[ i ] += -2;
i += 2 ;while ( arr[ i ] ) {
arr[ i ] += -1;
}
}
i += 1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
arr[ i ] += -1;
}
i += 1 ;while ( arr[ i ] ) {
i += -2 ;arr[ i ] += 1;
i += 2 ;arr[ i ] += -1;
}
i += 1 ;}
}
}
i += -1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -2 ;}
arr[ i ] += -1;
while ( arr[ i ] ) {
i += 2 ;}
i += -1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += 1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
i += -1 ;arr[ i ] += 1;
}
i += -2 ;while ( arr[ i ] ) {
i += -2 ;}
arr[ i ] += -1;
i += -1 ;while ( arr[ i ] ) {
i += 1 ;while ( arr[ i ] ) {
arr[ i ] += 1;
i += 2 ;}
i += 1 ;while ( arr[ i ] ) {
i += 1 ;}
i += 1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
}
}
i += 1 ;while ( arr[ i ] ) {
while ( arr[ i ] ) {
arr[ i ] += 1;
i += 2 ;}
i += -1 ;arr[ i ] += -2;
i += 2 ;while ( arr[ i ] ) {
i += 1 ;}
arr[ i ] += 1;
i += 3 ;}
}
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
while ( arr[ i ] ) {
arr[ i ] += -2;
while ( arr[ i ] ) {
arr[ i ] += 1;
i += -4 ;arr[ i ] += -2;
while ( arr[ i ] ) {
arr[ i ] += 1;
i += 1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
}
i += 1 ;while ( arr[ i ] ) {
i += -2 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
i += -2 ;while ( arr[ i ] ) {
i += 2 ;arr[ i ] += 1;
i += -2 ;arr[ i ] += -1;
}
}
arr[ i ] += 2;
while ( arr[ i ] ) {
i += 1 ;}
}
i += -2 ;while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += 1;
i += -2 ;arr[ i ] += -1;
}
i += 1 ;arr[ i ] += -2;
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
}
arr[ i ] += 2;
i += 3 ;}
i += -1 ;while ( arr[ i ] ) {
i += -3 ;while ( arr[ i ] ) {
arr[ i ] += -1;
}
arr[ i ] += 3;
i += 1 ;while ( arr[ i ] ) {
arr[ i ] += -1;
}
i += 1 ;while ( arr[ i ] ) {
i += -1 ;arr[ i ] += 1;
i += 3 ;arr[ i ] += 1;
i += -2 ;arr[ i ] += -1;
}
arr[ i ] += 1;
i += 3 ;}
}
i += -1 ;while ( arr[ i ] ) {
arr[ i ] += 1;
while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;}
i += -2 ;while ( arr[ i ] ) {
i += -2 ;}
arr[ i ] += -1;
i += -1 ;arr[ i ] += -1;
i += 2 ;arr[ i ] += 1;
i += 1 ;while ( arr[ i ] ) {
i += 2 ;}
i += 1 ;while ( arr[ i ] ) {
i += 1 ;}
i += -1 ;arr[ i ] += -1;
}
arr[ i ] += 1;
while ( arr[ i ] ) {
arr[ i ] += -1;
i += -1 ;arr[ i ] += 1;
}
i += -1 ;arr[ i ] += 2;
while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
arr[ i ] += 2;
i += -1 ;while ( arr[ i ] ) {
i += -2 ;arr[ i ] += -1;
i += 2 ;arr[ i ] += 1;
}
i += -1 ;arr[ i ] += 2;
}
i += -7 ;arr[ i ] += 1;
i += 3 ;arr[ i ] += 1;
i += 3 ;arr[ i ] += 1;
while ( arr[ i ] ) {
i += -3 ;arr[ i ] += -1;
i += 1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += 1;
while ( arr[ i ] ) {
i += -7 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
i += 1 ;arr[ i ] += 1;
i += 3 ;arr[ i ] += -1;
i += 1 ;arr[ i ] += -1;
i += 1 ;arr[ i ] += 1;
while ( arr[ i ] ) {
i += -5 ;arr[ i ] += -1;
i += 1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += 1;
i += 2 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += 1;
while ( arr[ i ] ) {
i += -4 ;arr[ i ] += -1;
i += 1 ;arr[ i ] += -1;
i += 1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
i += 1 ;arr[ i ] += 1;
while ( arr[ i ] ) {
i += -8 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
i += 2 ;arr[ i ] += 1;
i += 3 ;arr[ i ] += -1;
i += 1 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += 1;
while ( arr[ i ] ) {
i += -5 ;arr[ i ] += -1;
i += 2 ;arr[ i ] += 1;
i += 2 ;arr[ i ] += -1;
i += 1 ;arr[ i ] += 1;
while ( arr[ i ] ) {
i += -4 ;arr[ i ] += 1;
i += 1 ;arr[ i ] += -1;
i += 1 ;arr[ i ] += 1;
i += 2 ;arr[ i ] += 1;
}
}
}
}
}
}
}
arr[ i ] += 3;
while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += 1 ;arr[ i ] += 1;
i += -1 ;arr[ i ] += -1;
}
i += -1 ;arr[ i ] += 3;
}
arr[ i ] += -3;
i += 2 ;while ( arr[ i ] ) {
arr[ i ] += -1;
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += -1;
i += 1 ;arr[ i ] += -1;
}
i += -1 ;arr[ i ] += 2;
i += 2 ;}
arr[ i ] += 2;
while ( arr[ i ] ) {
while ( arr[ i ] ) {
i += -1 ;arr[ i ] += -1;
i += 1 ;arr[ i ] += -1;
}
i += 2 ;}
i += 1 ;while ( arr[ i ] ) {
i += 1 ;}
}
i += -1 ;}
}
i += -1 ;}
printf("\n");

free(arr);

}
